[versions]

activity-compose = "1.9.0"
android-gradle-plugin = "8.2.0"
compose-bom = "2024.06.00"
core-ktx = "1.13.1"
espresso-core = "3.6.1"
hilt = "2.51.1"
hilt-navigation-compose = "1.2.0"
junit = "4.13.2"
junit-ext = "1.2.1"
kotlin = "1.9.22"
kotlin-compose = "1.6.10"
ktlint = "0.43.0"
lifecycle = "2.8.3"
navigation-compose = "2.7.7"
vico = "2.0.0-beta02"

[libraries]

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }
vico-core = { module = "com.patrykandpatrick.vico:vico-core", version.ref = "vico" }
vico-compose = { module = "com.patrykandpatrick.vico:vico-compose", version.ref = "vico" }
vico-compose-m3 = { module = "com.patrykandpatrick.vico:vico-compose-m3", version.ref = "vico" }
vico-pie = { module = "com.patrykandpatrick.vico:vico-pie", version.ref = "vico" }


[bundles]

vico = ["vico-core", "vico-compose", "vico-compose-m3", "vico-pie"]

[plugins]

android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-compose" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
